Repository honeycombio/libhoney-rb, pull requests merged in 2021-07, with the labels that each got.

#89 Process single-error responses from the Batch API
  lib/libhoney/transmission.rb
  test/libhoney_test.rb
Labels: type: bug, version: bump minor

#87 add experimental transmission with new sized-and-timed queue
  .rubocop.yml
  lib/libhoney/client.rb
  lib/libhoney/experimental_transmission.rb
  lib/libhoney/mock_transmission.rb
  lib/libhoney/null_transmission.rb
  lib/libhoney/queueing.rb
  lib/libhoney/queueing/LICENSE.txt
  lib/libhoney/queueing/sized_queue_with_timeout.rb
  lib/libhoney/transmission.rb
  libhoney.gemspec
  test/experimental_transmission_test.rb
  test/libhoney_test.rb
  test/libhoney_w_experimental_transmission_test.rb
  test/queueing/sized_queue_with_timeout_test.rb
  test/stub_honeycomb_server.rb
  test/transmission_test.rb
Labels: status: review needed, type: bug, version: bump minor

#95 Handle Timeout::Error in TransmissionClient
  CONTRIBUTORS
  lib/libhoney/transmission.rb
Labels: version: bump patch
