Repository honeycombio/libhoney-rb, pull requests merged in 2024-03, with the labels that each got.

#139 maint: add labels to release.yml for auto-generated grouping
  .github/release.yml
Labels: type: maintenance, version: no bump, no-changelog

#138 feat: support classic-flavored ingest keys
  lib/libhoney.rb
  lib/libhoney/client.rb
  test/libhoney_test.rb
Labels: type: enhancement, version: bump minor

#140 rel: prepare v2.3.0
  CHANGELOG.md
  lib/libhoney/version.rb
Labels: version: no bump, no-changelog
